// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBscNTXDUP2omYc7eT_F0ooIoYm6P9Hwes',
    appId: '1:423868386363:web:f4d434512a4974963be01e',
    messagingSenderId: '423868386363',
    projectId: 'weather-49b06',
    authDomain: 'weather-49b06.firebaseapp.com',
    storageBucket: 'weather-49b06.appspot.com',
    measurementId: 'G-ZQK7QFQ9Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiBZG_UKRWFl8JN8O2JRLdc6b62VFtDPw',
    appId: '1:423868386363:android:cfe6165559604f913be01e',
    messagingSenderId: '423868386363',
    projectId: 'weather-49b06',
    storageBucket: 'weather-49b06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2BhY4OxLK6j4EoI0Dv22KFjRB39ydF6Y',
    appId: '1:423868386363:ios:e978f0cc8147365a3be01e',
    messagingSenderId: '423868386363',
    projectId: 'weather-49b06',
    storageBucket: 'weather-49b06.appspot.com',
    iosClientId: '423868386363-2d7n32upeedh5sbft5bk4i9blp8c69o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2BhY4OxLK6j4EoI0Dv22KFjRB39ydF6Y',
    appId: '1:423868386363:ios:027c8a53809c1e333be01e',
    messagingSenderId: '423868386363',
    projectId: 'weather-49b06',
    storageBucket: 'weather-49b06.appspot.com',
    iosClientId: '423868386363-qu255n14guq09c774oe97phk00nr8806.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheather.RunnerTests',
  );
}
